name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with: 
        node-version: '18.x'
        cache: 'npm'
        
    - uses: actions/hexlet-components/hello-from-hexlet-action@release
        
    - name: setup
      run: make setup

    - name: test
      run: make test

    - name: check linter
      run: make lint
